name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Run Job 1
      run: echo "Hallo von Job 1"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - name: Run Job 2
      run: echo "Hallo von Job 2"

  parallel-job:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
    - name: Run Parallel Job
      run: echo "Hallo vom Parallel Jobs"
